### PR TITLE
new blog post on Clojurebridge

### PR DESCRIPTION
**Pull request by deniseyu**

### CODE REVIEW

**Comment by despo** [comment]
@deniseyu You need to add this in the head (this is a copy paste from the Bath Ruby blog post)

```
---
layout: post
title: "Bath Ruby Conference 2015"
date: 2015-03-22 22:18:48 +0000
comments: true
author: Kriszta Matyi
author_email: matyi.kriszta@gmail.com
categories: bath ruby conference
---
```

**Comment by deniseyu** [comment]
oops - fixed now :D

**Comment by despo** [comment]
@deniseyu maybe change 'Denise' to 'I' -- since you are the author of the post.

**Comment by deniseyu** [comment]
haha ok. fixed

**Pull request merged**
