### PR TITLE
Responsive Day Out

### PR DESCRIPTION
**Pull request by Rosa-Fox**

### CODE REVIEW

**Comment by matyikriszta** [comment]
hey @Rosa-Fox is this done, can it go live next Monday?

**Comment by Rosa-Fox** [comment]
Aloha,

Cool thanks, do you mean Monday 13th?

**Comment by matyikriszta** [comment]
yeah, that's what I meant, or around that time

**Comment by Rosa-Fox** [comment]
:+1:

**Comment by matyikriszta** [comment]
thanks :+1:

**Comment by matyikriszta** [comment]
oh dang, I just noticed something, could you change all references to codebar to a lower case c? c as opposed to C?

**Pull request merged**
